name: Accessibility Check

on:
  push:
    branches:
      - testbot/508-pa11y-test-run

jobs:
  a11y-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Pa11y
        run: npm install -g pa11y

      - name: Run Pa11y Accessibility Tests
        run: |
          pa11y https://about.google/ --standard WCAG2AA --timeout 120000 --debug
          pa11y https://blog.google/inside-google/doodles/ --standard WCAG2AA --timeout 120000 --debug
          pa11y https://blog.google/outreach-initiatives/public-policy/ --standard WCAG2AA --timeout 120000 --debug
